---
- import_playbook: playbook_launch_pre_tasks.yml

- name: Run Loader
  hosts: remote
  user: core
  gather_facts: False

  vars:
    API_ACCESS_TOKEN: "{{ LOADER_BUILD_API_ACCESS_TOKEN }}"

  vars_files:
    - "environments/{{ env }}/main.yml" # ENV must always be loaded first
    - "environments/shared_secrets.yml"
    - "environments/shared_variables.yml"

  tasks:
    - name: Login to Docker
      block:
        - include_tasks: tasks/docker_login.yml
        - set_fact:
            failed_flag: "passed"
      rescue:
        - debug:
            msg: "Failed execute docker login."
        - set_fact:
            failed_flag: "failed"
    - name: Build Loader, Run Loader
      block:
        - include_tasks: tasks/build_loader.yml
        - include_tasks: tasks/run_loader.yml
        - set_fact:
            failed_flag: "passed"
      rescue:
        - debug:
            msg: "Error Detected Failing Build"
        - set_fact:
            failed_flag: "failed"

    - name: Run Loader Tests
      block:
        - include_tasks: tasks/run_loader_tests.yml
        - set_fact:
            failed_flag: "passed"
      rescue:
        - debug:
            msg: "Error Detected Failing Build"
        - set_fact:
            failed_flag: "failed"
      when: RUN_LOADER_TESTS


- name: Check Failures
  hosts: remote
  gather_facts: False
  tasks:
    - fail:
        msg: "The execution has failed because of errors."
      when: failed_flag == "failed"
