---
- import_playbook: playbook_launch_pre_tasks.yml

- name: Run Neo
  hosts: remote
  user: core
  gather_facts: False

  vars_files:
    - "environments/{{ env }}/main.yml" # ENV must always be loaded first
    - "environments/shared_secrets.yml"
    - "environments/shared_variables.yml"

  tasks:
    - name: Start Neo ENV
      block:
        - include_tasks: tasks/start_neo_env.yml
        - set_fact:
            failed_flag: "passed"
      rescue:
        - debug:
            msg: "Error Detected Failing Build"
        - set_fact:
            failed_flag: "failed"
      when: not DOWNLOAD_NEO4J_DATA_IMAGE_FROM_AWS

    - name: Start Neo Data
      block:
        - include_tasks: tasks/start_neo_data.yml
        - set_fact:
            failed_flag: "passed"
      rescue:
        - debug:
            msg: "Error Detected Failing Build"
        - set_fact:
            failed_flag: "failed"
      when: DOWNLOAD_NEO4J_DATA_IMAGE_FROM_AWS


- name: Check Failures
  hosts: remote
  gather_facts: False
  tasks:
    - fail:
        msg: "The execution has failed because of errors."
      when: failed_flag == "failed"
