---

- import_playbook: playbook_launch_pre_tasks.yml

- name: Run QC
  hosts: remote
  user: core
  gather_facts: False

  vars_files:
    - "environments/{{ env }}/main.yml" # ENV must always be loaded first
    - "environments/shared_secrets.yml"
    - "environments/shared_variables.yml"

  tasks:
    - name: Build QC, Run QC
      block:
        - include_tasks: tasks/build_qc.yml
        - include_tasks: tasks/run_qc.yml
        - set_fact:
            failed_flag: "passed"
      rescue:
        - debug:
            msg: "Error Detected Failing Build"
        - set_fact:
            failed_flag: "failed"


- name: Check Failures
  hosts: remote
  gather_facts: False
  tasks:
    - fail:
        msg: "The execution has failed because of errors."
      when: failed_flag == "failed"
