---
- name: Terminate Instance
  hosts: local
  connection: local
  gather_facts: false

  vars_files:
    - "environments/{{ env }}/main.yml" # ENV must always be loaded first
    - "environments/shared_secrets.yml"
    - "environments/shared_variables.yml"

  tasks:
    - name: Obtaining EC2 Instance Info
      ec2_instance_facts:
        aws_access_key: "{{ AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        region: "us-east-1"
        filters:
          "tag:Name": "Ansible Generated - {{ NET }}-dev Server"
          "instance-state-name": "running"
      register: ec2info

    - name: Terminating EC2 Instance {{ ec2info.instances[0].instance_id }}
      ec2:
        aws_access_key: "{{ AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        region: "us-east-1"
        instance_ids: "{{ ec2info.instances[0].instance_id }}"
        state: absent
