---

- name: Recursively remove directory
  file:
    path: agr_indexer
    state: absent

- git:
    repo: 'git@github.com:alliance-genome/agr_java_software.git'
    version: "{{ GITHUB_JAVA_SOFTWARE_BRANCH }}"
    dest: "agr_java_software"

- name: Build the indexer docker image
  command: docker build --build-arg REG={{ REGISTRY }} --build-arg ALLIANCE_RELEASE={{ ALLIANCE_RELEASE }} -t "{{ JAVA_SOFTWARE_IMAGE_NAME }}" agr_indexer
