---

- name: Recursively remove directory
  ignore_errors: yes # If the directory is missing, ignore the error.
  file:
    path: agr_qc
    state: absent

- name: Create directory
  file:
    path: agr_qc
    state: directory

- git:
    repo: 'git@github.com:alliance-genome/agr_qc.git'
    version: "{{ GITHUB_QC_BRANCH }}"
    dest: "agr_qc"

- name: Build the qc docker image
  command: docker build --build-arg REG={{ REGISTRY }} --build-arg ALLIANCE_RELEASE={{ ALLIANCE_RELEASE }} -t "{{ QC_TEST_IMAGE_NAME }}" agr_qc
