---

- name: Recursively remove directory
  file:
    path: agr_loader
    state: absent

- git:
    repo: 'https://github.com/alliance-genome/agr_loader.git'
    version: "{{ GITHUB_LOADER_BRANCH }}"
    dest: "agr_loader"

- name: Build the loader docker image
  command: docker build --build-arg REG={{ REGISTRY }} --build-arg ALLIANCE_RELEASE={{ ALLIANCE_RELEASE }} -t "{{ LOADER_TEST_RUN_IMAGE_NAME }}" agr_loader
