- name: Pulling Loader Image {{ LOADER_IMAGE_NAME }} from AWS ECR
  docker_image:
    name: "{{ LOADER_IMAGE_NAME }}"
    source: pull
    force_source: "{{ PULL_UPDATES }}"
  when: DOWNLOAD_LOADER_IMAGE_FROM_AWS

- name: Recursively removing directory agr_loader
  ignore_errors: yes # If the directory is missing, ignore the error.
  file:
    path: agr_loader
    state: absent
  when: not DOWNLOAD_LOADER_IMAGE_FROM_AWS

- name: Creating directory agr_loader
  file:
    path: agr_loader
    state: directory
  when: not DOWNLOAD_LOADER_IMAGE_FROM_AWS

- git:
    repo: 'https://github.com/alliance-genome/agr_loader.git'
    version: "{{ GITHUB_LOADER_BRANCH }}"
    dest: "agr_loader"
  when: not DOWNLOAD_LOADER_IMAGE_FROM_AWS

- name: Building the loader docker image using the branch {{ GITHUB_LOADER_BRANCH }} from GitHub
  command: docker build --build-arg REG={{ REGISTRY }} --build-arg ALLIANCE_RELEASE={{ ALLIANCE_RELEASE }} -t "{{ LOADER_IMAGE_NAME }}" agr_loader
  when: not DOWNLOAD_LOADER_IMAGE_FROM_AWS
