- name: Pulling AWS CLI image amazon/aws-cli:latest
  docker_image:
    name: amazon/aws-cli:latest
    source: pull

- name: Creating AWS ECR Token (Good only for 12 hours)
  raw: docker run -it --rm amazon/aws-cli ecr get-login-password --region us-east-1
  register: docker_output

- name: Logging into AWS ECR via Docker
  docker_login:
    registry_url: "{{ REGISTRY }}"
    username: "AWS"
    password: "{{ docker_output.stdout_lines[0] }}"
  become: true
  become_user: core