- name: Docker pull cli image
  docker_image:
    name: amazon/aws-cli:latest

- name: AWS Create ECR Token (Good only for 12 hours)
  raw: docker run -it --rm amazon/aws-cli ecr get-login-password --region us-east-1
  register: docker_output

- name: Docker Login
  docker_login:
    registry_url: "{{ REGISTRY }}"
    username: "AWS"
    password: "{{ docker_output.stdout_lines[0] }}"
  become: true
  become_user: core