---
- name: Pulling Loader Image {{ LOADER_IMAGE_NAME }} from AWS ECR
  docker_image:
    name: "{{ LOADER_IMAGE_NAME }}"
    source: pull
    force_source: "{{ PULL_UPDATES }}"
  when: DOWNLOAD_LOADER_IMAGE_FROM_AWS

- name:
  docker_container:
    name: "{{ LOADER_RUN_NAME }}"
    image: "{{ LOADER_IMAGE_NAME }}"
    command: conda run -n agr_loader --no-capture-output pytest --verbose -n=10
    detach: no
    recreate: yes
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    volumes:
      - "{{ NEO_VOLUME_NAME }}:/usr/src/app/tmp"
    networks:
      - name: "{{ NET }}"
    env:
      API_KEY: "{{ API_ACCESS_TOKEN }}"
      DEBUG: "False"
      DOWNLOAD_HOST: "{{ DOWNLOAD_HOST }}"
      TEST_SET: "{{ LOADER_TEST_SET | string }}"
      ALLIANCE_RELEASE: "{{ ALLIANCE_RELEASE }}"
      FMS_API_URL: "{{ FMS_API_URL }}"
      AWS_ACCESS_KEY: "{{ AWS_ACCESS_KEY }}"
      AWS_SECRET_KEY: "{{ AWS_SECRET_KEY }}"
      GENERATE_REPORTS: "{{ GENERATE_REPORTS | string }}"
      NEO4J_HOST: "{{ NEO_SERVER_NAME }}"