- name: Running Human Variant Indexer
  docker_container:
    name: "{{ HUMAN_VARIANT_INDEXER_RUN_NAME }}"
    image: "{{ JAVA_SOFTWARE_RUN_IMAGE_NAME}}"
    detach: no
    recreate: yes
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    volumes:
      - "agr_variant_data:/workdir/agr_java_software/data"
    networks:
      - name: "{{ NET }}"
    env:
      ES_HOST: "{{ ES_SERVER_NAME }}"
      NEO4J_HOST: "{{ NEO_SERVER_NAME }}"
      BOLT_LOG_LEVEL: INFO
      DEFAULT_LOG_LEVEL: INFO

      ES_INDEX_PREFIX: "human"
      ES_INDEX: "variant_index"
      ES_INDEX_SUFFIX: "{{ NET }}"
      VARIANTS_TO_INDEX: "HUMAN"
      VARIANT_INDEXER_SHARDS: "64"
      VARIANT_SOURCE_DOCUMENT_CREATOR_VCQUEUE_SIZE: "400"
      VARIANT_SOURCE_DOCUMENT_CREATOR_VCQUEUE_BUCKET_SIZE: "25"
      VARIANT_SOURCE_DOCUMENT_CREATOR_OBJECT_QUEUE_SIZE: "500"
      VARIANT_SOURCE_DOCUMENT_CREATOR_OBJECT_QUEUE_BUCKET_SIZE: "50"
      VARIANT_PRODUCER_THREADS: "12"

      VARIANT_TRANSFORMER_THREADS: "12"
      VARIANT_INDEXER_BULK_PROCESSOR_THREADS: "10"
      VARIANT_BULK_PROCESSOR_SETTINGS: "10000;20;10;1500;1000,133;20;10;1333;7500,100;20;10;1000;10000,50;20;10;500;10000000"

    command: java -Xms{{ INDEXER_MEMORY }} -Xmx{{ INDEXER_MEMORY }} -DTHREADED={{ THREADED }} -jar agr_variant_indexer/target/agr_variant_indexer-jar-with-dependencies.jar
