- name: Running Mod Variant Indexer
  docker_container:
    name: "{{ MOD_VARIANT_INDEXER_RUN_NAME }}"
    image: "{{ JAVA_SOFTWARE_RUN_IMAGE_NAME}}"
    detach: no
    recreate: yes
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    volumes:
      - "agr_variant_data:/workdir/agr_java_software/data"
    networks:
      - name: "{{ NET }}"
    env:
      ES_HOST: "es01,es02,es03,es04,es05,es06,es07,es08"
      NEO4J_HOST: "{{ NEO_SERVER_NAME }}"
      BOLT_LOG_LEVEL: INFO
      DEFAULT_LOG_LEVEL: INFO

      ES_INDEX_PREFIX: "mod"
      ES_INDEX: "variant_index"
      ES_INDEX_SUFFIX: "{{ NET }}"
      VARIANTS_TO_INDEX: "MOD"
      VARIANT_INDEXER_SHARDS: "16"
      VARIANT_PRODUCER_THREADS: "20"
      VARIANT_SOURCE_DOCUMENT_CREATOR_THREADS: "8"
      #VARIANT_BULK_PROCESSOR_SETTINGS: "10000;4;10;10000;1000,133;4;10;1333;7500,100;4;10;1000;10000,50;4;10;500;10000000"
      #VARIANT_BULK_PROCESSOR_SETTINGS: "25000;1;10;750;400,13333;1;10;425;750,6666;1;10;200;1500,1000;1;10;100;1000000"
      VARIANT_BULK_PROCESSOR_SETTINGS: "100000;5;6;5000;400,100000;5;6;1800;750,100000;5;6;1000;1500,100000;5;6;1000;1000000"

    command: java -Xms{{ INDEXER_MEMORY }} -Xmx{{ INDEXER_MEMORY }} -DTHREADED={{ THREADED }} -jar agr_variant_indexer/target/agr_variant_indexer-jar-with-dependencies.jar
