- name: Creating DockerHub config directory
  file:
    path: /home/core/.docker
    state: directory
    mode: 0755

- name: Copying DockerHub config file
  copy:
    content: "{{ DockerHubCredsFile }}"
    dest: "/home/core/.docker/config.json"
    mode: 0644

- name: Creating SSL directory
  file:
    path: /home/core/ssl
    state: directory
    mode: 0755

- name: Setting permissions on Docker sock file
  file:
    path: /var/run/docker.sock
    mode: o+rw
  become: true
  become_user: root

- name: Copying SSL CRT file
  copy:
    content: "{{ AGR_WEB_CRT_FILE }}"
    dest: "/home/core/ssl/agr.crt"
    mode: 0644

- name: Copying SSL KEY File
  copy:
    content: "{{ AGR_WEB_KEY_FILE }}"
    dest: "/home/core/ssl/agr.key"
    mode: 0644

- name: Copying CA file
  copy:
    src: files/ca-certs.pem
    dest: "/home/core/ssl/ca-certs.pem"
    mode: 0644

- name: Creating the docker network {{ NET }}
  docker_network:
    name: "{{ NET }}"

- name: Setting max opened files
  sysctl:
    name: vm.max_map_count
    value: '262144'
    sysctl_set: yes
    state: present
    reload: yes
  become: true
  become_user: root

- name: Turning off locksmithd
  service:
    name: locksmithd
    state: stopped
  become: true
  become_user: root
