- name: Pulling ES Env Image {{ ES_ENV_IMAGE_NAME }}
  docker_image:
    name: "{{ ES_ENV_IMAGE_NAME }}"
    source: pull

- name: Pulling Cerebro Image
  docker_image:
    name: "yannart/cerebro:latest"
    source: pull

- name: Starting Elasticsearch
  docker_container:
    name: "{{ ES_SERVER_NAME }}"
    image: "{{ ES_ENV_IMAGE_NAME }}"
    networks:
      - name: "{{ NET }}"
    ports:
      - "9200:9200"
      - "9300:9300"
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    env:
      discovery.type: single-node

- name: Starting Cerebro
  docker_container:
    name: "agr.{{ env }}.cerebro.server"
    image: "yannart/cerebro:latest"
    networks:
      - name: "{{ NET }}"
    ports:
      - "9000:9000"

- name: Pulling Logstash Image {{ LOG_IMAGE_NAME }}
  docker_image:
    name: "{{ LOG_IMAGE_NAME }}"
    source: pull

- name: Starting Logstash Server
  docker_container:
    name: "{{ LOG_SERVER_NAME }}"
    image: "{{ LOG_IMAGE_NAME }}"
    networks:
      - name: "{{ NET }}"
    env:
      xpack.monitoring.elasticsearch.hosts: "http://{{ ES_SERVER_NAME }}:9200"
    ports:
      - "9600:9600"
      - "12201:12201/udp"
    command: ./bin/logstash -e "input { gelf { type => docker } } output { elasticsearch { hosts => [\"{{ ES_SERVER_NAME }}\"] ilm_enabled => true ilm_policy => \"ilm-history-ilm-policy\" } }"

- name: Pulling Kibana Image {{ KIBANA_IMAGE_NAME }}
  docker_image:
    name: "{{ KIBANA_IMAGE_NAME }}"
    source: pull

- name: Starting Kibana
  docker_container:
    name: "{{ KIBANA_SERVER_NAME }}"
    image: "{{ KIBANA_IMAGE_NAME }}"
    env:
      ELASTICSEARCH_HOSTS: "http://{{ ES_SERVER_NAME }}:9200"
    networks:
      - name: "{{ NET }}"
    ports:
      - "5601:5601"
