- name: Pulling Neo4j Env Image {{ NEO_ENV_IMAGE_NAME }}
  docker_image:
    name: "{{ NEO_ENV_IMAGE_NAME }}"
    source: pull
    force_source: "{{ PULL_UPDATES }}"

- name: Creating Neo4j Shared Volume
  docker_volume:
    name: "{{ NEO_VOLUME_NAME }}"

- name: Starting Neo4j
  docker_container:
    name: "{{ NEO_SERVER_NAME }}"
    image: "{{ NEO_ENV_IMAGE_NAME }}"
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - "{{ NEO_VOLUME_NAME }}:/var/lib/neo4j/import"
    networks:
      - name: "{{ NET }}"
    env:
      # NEO4J_dbms_memory_pagecache_size: "{{ NEO_PAGE_CACHE }}"
      # NEO4J_dbms_memory_heap_maxSize: "{{ NEO_MAX_HEAP }}"
      NEO4J_AUTH: "none" 

- name: Waiting for Neo4j to come online
  shell: docker exec -t {{ NEO_SERVER_NAME }} \
    bash -c "until echo 'match (n) return count(n);' | bin/cypher-shell -a bolt://localhost:7687; do echo $? ; sleep 1; done"
  register: result
  until: result.stdout.find("count")
  retries: 60
  delay: 10