- name: Pull Kibana Image
  docker_image:
    name: "{{ KIBANA_IMAGE_NAME }}"

- name: Run Kibana
  docker_container:
    name: "{{ KIBANA_SERVER_NAME }}"
    image: "{{ KIBANA_IMAGE_NAME }}"
    networks:
      - name: "{{ NET }}"
    ports:
      - "5601:5601"
    env:
      ELASTICSEARCH_HOSTS: "http://{{ ES_SERVER_NAME }}:9200"
      discovery.type: single-node