- name: Pulling Neo4j Data Image {{ NEO_DATA_IMAGE }}
  docker_image:
    name: "{{ NEO_DATA_IMAGE }}"
    source: pull
    force_source: "{{ PULL_UPDATES }}"

- name: Creating Neo4j Shared Volume
  docker_volume:
    name: "{{ NEO_VOLUME_NAME }}"

- name: Starting Neo4j
  docker_container:
    name: "{{ NEO_SERVER_NAME }}"
    image: "{{ NEO_DATA_IMAGE }}"
    log_driver: "gelf"
    recreate: yes
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - name: "{{ NET }}"
    env:
      NEO4J_server_memory_heap_max__size: "{{ NEO_MAX_HEAP }}"
      NEO4J_server_memory_heap_initial__size: "{{ NEO_MAX_HEAP }}"
      NEO4J_server_memory_off__heap_max__size: "{{ NEO_OFF_HEAP_MAX }}"
      NEO4J_server_memory_pagecache_size: "{{ NEO_PAGE_CACHE }}"
      NEO4J_db_tx__state_memory__allocation: "{{ NEO_ON_OFF_HEAP }}"
      NEO4J_dbms_memory_transaction_total_max: "{{ NEO_TRANSACTION}}"
      NEO4J_db_memory_transaction_total_max: "{{ NEO_TRANSACTION}}"
      NEO4J_db_memory_transaction_max: "{{ NEO_TRANSACTION}}"
      NEO4J_AUTH: "none"

- name: Waiting for Neo4j to come online
  shell: docker exec -t {{ NEO_SERVER_NAME }} \
    bash -c "until echo 'match (n) return count(n);' | bin/cypher-shell -a bolt://localhost:7687; do echo $? ; sleep 1; done"
  register: result
  until: result.stdout.find("count")
  retries: 60
  delay: 10