- name: Stopping ES Server
  docker_container:
    name: "{{ ES_SERVER_NAME }}"
    state: absent
- name: Stopping Cerebro Server
  docker_container:
    name: "agr.{{ env }}.cerebro.server"
    state: absent
- name: Stopping Logstash Server
  docker_container:
    name: "{{ LOG_SERVER_NAME }}"
    state: absent
- name: Stopping Kibana Server
  docker_container:
    name: "{{ KIBANA_SERVER_NAME }}"
    state: absent
